<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>forge</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="YamlDotNet" Version="16.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Forge.Contracts/Forge.Contracts.csproj" />
    <ProjectReference Include="../Forge.Database/Forge.Database.csproj" />
    <ProjectReference Include="../Forge.Environments/Forge.Environments.csproj" />
    <ProjectReference Include="../Forge.Packaging/Forge.Packaging.csproj" />
  </ItemGroup>
</Project>
